Implementing vale
pyansys/grantami-bomanalytics pull request #251
Opened 2022-12-16 07:34 UTC by RobPasMue

As title says and coming from request on #249 by @PipKat 

I'll leave you the error resolutions! =)

2022-12-16 16:42 UTC, PipKat commented
@RobPasMue All remaining Value issues can be resolved by excluding this folder from the Granta MI BomAnalaytics Vale check: C:\AnsysDev\GitRepos\PyAnsys\grantami-bomanalytics\doc\source\_templates. I tried adding "-templates" to exclude_patterns in the config.py file but that didn't work. Also @Andy-Grigg, primariliy so that you know that Vale is implemented and only removing the _templates folder from the check is left to do.

2022-12-16 18:14 UTC, Andy-Grigg commented
Thanks for implementing this! I'm (mostly) off today and Monday, but I'll get this finished off next week.

2022-12-16 20:43 UTC, RobPasMue commented
Hey there! @Andy-Grigg @PipKat - I briefly discussed with Kathy, the way Vale works is basically "the other way around". You tell the tool which files to consider. And the way we have it configured in PyAnsys actions is to consider the entire "doc" folder. If you want to try and work around it, I suggest we implement the action "on our own" https://github.com/pyansys/actions/blob/main/doc-style/action.yml

This might be a bit tricky though... wouldn't it be easier to just solve the issues in the templates or ignore Vale in the files with the use of the pragmas ``.. vale off / .. vale on```? Depending on:
* If it is an HTML file or Markdown: https://vale.sh/docs/topics/config/#markdown-amp-html
* If it is an rST file: https://vale.sh/docs/topics/config/#restructuredtext

2022-12-20 15:16 UTC, PipKat commented
@Andy-Grigg I implemented .. vale off/.. vale in the RST files in the _templates folder. There are no longer Vale errors. I've approved but will let you decide if you want to merge.

2022-12-20 15:17 UTC, PipKat approved these changes
All Vale errors now resolved. LGTM.

2022-12-20 19:40 UTC, PipKat commented on src/ansys/grantami/bomanalytics/queries.py
> +        determines whether a query be performed on the items in the object.
```suggestion
        determines whether to perform a query on the items in the object.
```

2022-12-20 20:05 UTC, Andy-Grigg requested changes

2022-12-20 20:28 UTC, PipKat commented on examples/0_Getting_started.py
> +query = (
@Andy-Grigg I THINK I restored it correctly. Please resolve the conversation if so.

2022-12-20 20:29 UTC, PipKat commented on examples/0_Getting_started.py
> +query = queries.MaterialImpactedSubstancesQuery().with_material_ids(["plastic-abs-high-impact"]).with_legislations(["REACH - The Candidate List"]))  # noqa: E501
```suggestion
query = queries.MaterialImpactedSubstancesQuery().with_material_ids(["plastic-abs-high-impact"]).with_legislations(["REACH - The Candidate List"])  # noqa: E501
```

2022-12-20 21:08 UTC, Andy-Grigg approved these changes

2022-12-20 21:10 UTC, merged